apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql
spec:
  capacity:
    storage: 10Gi  # Capacité de stockage
  accessModes:
    - ReadWriteOnce  # Un seul nœud peut écrire
  persistentVolumeReclaimPolicy: Retain  # Garde les données même après suppression du PVC
  storageClassName: manual
  hostPath:
    path: /data-mysql  # Chemin du stockage sur l’hôte

